### ISSUE TITLE
Not compatible with version 1.42.1

### ISSUE THREAD

**Issue by sathwik77** [expo-community/vscode-expo#7]
### Topic and scope of discussion
Unable to install this extension on some versions of VSCode in MacOS

### Motivation
Want to know which versions of VS Code is supported.

### Additional context
![Screen Shot 2563-07-15 at 11 47 41](https://user-images.githubusercontent.com/26072324/87504553-05e9fe00-c691-11ea-8e66-3f4ba232178d.png)

**Comment by byCedric** [comment]
Ah, let me check, I think this might be related to some weird configuration. It's not doing a lot here so it should be compatible.

**Comment by sathwik77** [comment]
Yeah I updated my VS code to `^1.44.0` and its working, anyway  just wanted to know which versions this is supported. Thanks :)
